const { SlashCommandBuilder } = require('@discordjs/builders');
const { MessageActionRow, MessageButton, MessageEmbed, MessageSelectMenu } = require('discord.js');

const fetch = require('node-fetch');
const { apiUrl, apiKey } = require('../config.json');

const Utils = require('../utils.js');


let effectsMap = new Map([
  ['bludgeoning', [
    {name: `CRUNCH`, text: `**Crit Effect:** The target is sickened 3.`},
    {name: `WHERE AM I?`, text: `Normal damage. **Crit Effect:** The target is stunned 2.`},
    {name: `SURPRISE OPENING`, text: `**Crit Effect:** You gain 1 action that you can use before the end of your turn to use an attack action against the target.`},
    {name: `CRACKED RIB`, text: `The target is fatigued.`},
    {name: `FEEBLE PARRY`, text: `**Crit Effect:** The target drops one weapon it's wielding, determined by the GM.`},
    {name: `CRACKED KNEE`, text: `**Crit Effect:** Until healed, the target is clumsy 2 and takes a -5-foot status penalty to land Speed.`},
    {name: `BELL RINGER`, text: `**Crit Effect:** The target is sickened 2, and it is stupefied 2 until it is no longer sickened.`},
    {name: `SPLIT OPEN`, text: `**Crit Effect:** The target takes 1d6 persistent bleed damage.`},
    {name: `MOMENTUM`, text: `You gain a +2 circumstance bonus to all attack rolls until the end of your next turn.`},
    {name: `I SEE STARS`, text: `Normal damage. **Crit Effect:** The target is dazzled until healed.`},
    {name: `BROKEN NOSE`, text: `The target takes 1d4 persistent bleed damage.`},
    {name: `CRUSHED TOE`, text: `Normal damage. The target is clumsy 2 and takes a -10-foot status penalty to land Speed. Both effects last until healed.`},
    {name: `NUMBING BLOW`, text: `Normal damage. **Crit Effect:** The target is clumsy 1 for 1 minute and must succeed at a Reflex save or drop one item it holds at random.`},
    {name: `CRUMPLING BLOW`, text: `The target is knocked prone.`},
    {name: `SHATTERED HAND`, text: `Normal damage. Until healed, the target is clumsy 2 and enfeebled 2, and it can't use one of its hands (chosen randomly by the GM).`},
    {name: `TWO FOR ONE`, text: `**Crit Effect:** Deal normal damage to one target adjacent to the original target.`},
    {name: `AND STAY DOWN!`, text: `Normal damage. **Crit Effect:** The target is knocked prone and stunned 2.`},
    {name: `RATTLED`, text: `Normal damage. **Crit Effect:** The target is confused for 1 round.`},
    {name: `NIGHTY NIGHT`, text: `Normal damage. **Crit Effect:** The target falls unconscious and can't wake up until the end of its next turn.`},
    {name: `BRAINED`, text: `The target is stunned 1.`},
    {name: `COLLAPSED LUNG`, text: `Normal damage. **Crit Effect:** Until healed, the target is enfeebled 2 and fatigued.`},
    {name: `BONE MASHER`, text: `Normal damage. **Crit Effect:** Either the target is clumsy 2 and takes a -10-foot status penalty to land Speed or is clumsy 2 and can't use one of its arms (your choice). Either effect lasts until healed.`},
    {name: `OVERWHELMING SMASH`, text: `Triple damage.`},
    {name: `RUPTURED SPLEEN`, text: `Normal damage. **Crit Effect:** The target takes 1 persistent bleed damage that can't be removed until the target has been subject to magical healing.`},
    {name: `OFF BALANCE`, text: `The target triggers reactions as if it just used a move action. It is also flat-footed until the end of its next turn.`},
    {name: `CRUSHED INTESTINES`, text: `Normal damage. **Crit Effect:** The target is wounded 2 and enfeebled 2 until it is no longer wounded.`},
    {name: `CRUSHED TRACHEA`, text: `**Crit Effect:** The target is suffocating (CRB pg. 478) until subject to magical healing. It can't speak while it is suffocating.`},
    {name: `SKULL CRUSH`, text: `**Crit Effect:** The target is stupefied 3 until healed.`},
    {name: `CAVED SKULL`, text: `Triple damage. **Crit Effect:** The target must succeed at a Fortitude save or die.`},
    {name: `TO YOUR THINKY BITS`, text: `**Crit Effect:** The target is stupefied 2 until healed.`},
    {name: `DAZING THUD`, text: `The target is stunned 1.`},
    {name: `CLOCKED!`, text: `Triple damage. The target is knocked prone.`},
    {name: `BROKEN RIBS`, text: `Normal damage. **Crit Effect:** The target is slowed 1 until healed.`},
    {name: `STAGGERING BLOW`, text: `**Crit Effect:** The target is stunned 2.`},
    {name: `THUNDER STRIKE`, text: `**Crit Effect:** The target is deafened until healed.`},
    {name: `BOX THE EARS`, text: `The target is deafened until healed.`},
    {name: `CONCUSSION`, text: `Normal damage. The target is confused for 1 minute and stupefied 2 until healed.`},
    {name: `ARMOR DENT`, text: `Normal damage. **Crit Effect:** Deal the same amount of damage to the target's armor, ignoring that armor's Hardness.`},
    {name: `SOUL-CRUSHING BLOW`, text: `**Crit Effect:** The target is doomed 1 and is stupefied 1 for as long as it is doomed.`},
    {name: `BREATHLESS`, text: `The target is fatigued.`},
    {name: `BROKEN LEG`, text: `**Crit Effect:** The target takes a -15-foot status penalty to its land Speed until healed.`},
    {name: `SHIELD SMACK`, text: `**Crit Effect:** The target must succeed at a Reflex save or drop a shield it's holding.`},
    {name: `MY TEEF!`, text: `The target must succeed at a DC 5 flat check to cast spells with the verbal component until healed.`},
    {name: `KNOCKBACK`, text: `**Crit Effect:** The target is pushed 1d4x5 feet away.`},
    {name: `LOW BLOW`, text: `**Crit Effect:** The target is sickened 2 and slowed 1 as long as it remains sickened.`},
    {name: `BUSTED SHIN`, text: `**Crit Effect:** Until healed, the target is clumsy 1 and takes a -10-foot status penalty to its land Speed.`},
    {name: `BACK BREAKER`, text: `**Crit Effect:** Until healed, the target is clumsy 2 and enfeebled 2.`},
    {name: `SOLID BLOW`, text: `Triple damage.`},
    {name: `TIRING BLOW`, text: `The target is fatigued.`},
    {name: `FOOT SMASH`, text: `The target is flat-footed until the end of its next turn.`},
    {name: `LIGHTS OUT`, text: `**Crit Effect:** The target is blinded until the end of its next turn.`},
    {name: `ROUNDHOUSE`, text: `**Crit Effect:** Make one additional attack against a foe adjacent to the original target, using the same attack modifier as the original attack.`},
  ]],
  ['piercing', [
    {name: `FOREARM PIERCING`, text: `**Crit Effect:** The target drops one weapon it's holding (chosen randomly by the GM).`},
    {name: `SURPRISE OPENING`, text: `**Crit Effect:** You gain 1 action that you can use before the end of your turn to use an attack action against the target.`},
    {name: `TONGUE PIERCING`, text: `The target must succeed at a DC 5 flat check to cast spells with the verbal component until healed.`},
    {name: `MOMENTUM`, text: `You gain a +2 circumstance bonus to all attack rolls until the end of your next turn.`},
    {name: `SHOULDER WOUND`, text: `**Crit Effect:** Until healed, the target is clumsy 1 and enfeebled 2.`},
    {name: `CALF JAB`, text: `**Crit Effect:** Until healed, the target is clumsy 1 and takes a -10-foot status penalty to land Speed.`},
    {name: `SKEWERED`, text: `Triple damage. **Crit Effect:** The target is slowed 1 for 1 round.`},
    {name: `SEND 'EM REELING`, text: `**Crit Effect:** The target is flat-footed until the end of its next turn.`},
    {name: `BLOWBACK`, text: `The target is knocked prone.`},
    {name: `PINHOLE`, text: `**Crit Effect:** The target takes 1 persistent bleed damage that can't be removed until the target is healed.`},
    {name: `TWO IN A ROW`, text: `**Crit Effect:** Deal normal damage to an additional target adjacent to the original target.`},
    {name: `STINGER`, text: `Normal damage. The target is sickened 3.`},
    {name: `SUCKING CHEST WOUND`, text: `The target is fatigued.`},
    {name: `PIERCED`, text: `The target is slowed 1 until the end of its next turn.`},
    {name: `RIGHT IN THE EAR`, text: `Normal damage. The target is deafened until healed.`},
    {name: `PINNED ARM`, text: `As the bow critical specialization effect, and the target can't use one of its arms until freed. If using a melee weapon, you must drop it to gain this effect.`},
    {name: `VENTILATED`, text: `Triple damage.`},
    {name: `GUARDED STRIKE`, text: `**Crit Effect:** Gain a +2 circumstance bonus to AC until the end of your next turn.`},
    {name: `PAINFUL POKE`, text: `The target is stunned 1.`},
    {name: `KIDNEY PIERCING`, text: `The target is sickened 2.`},
    {name: `NERVE CLUSTER`, text: `Normal damage. **Crit Effect:** The target is stunned 2.`},
    {name: `PUNCTURED LUNG`, text: `**Crit Effect:** The target is suffocating (CRB pg. 478) until subject to magical healing.`},
    {name: `NICKED AN ARTERY`, text: `Normal damage. **Crit Effect:** The target takes 2d6 persistent bleed damage.`},
    {name: `MUSCLE SEVERED`, text: `Normal damage. **Crit Effect:** Until healed, the target is clumsy 3 and enfeebled 3.`},
    {name: `CHIPPED BONE`, text: `The target is clumsy 1 until healed.`},
    {name: `LODGED IN THE BONE`, text: `**Crit Effect:** The target takes 1d6 persistent bleed damage.`},
    {name: `PIERCED ELBOW`, text: `The target drops one item it is holding (determined randomly by the GM).`},
    {name: `HAND WOUND`, text: `**Crit Effect:** Until healed, the target is clumsy 2 and can't use one of its hands (determined randomly by the GM).`},
    {name: `OVERREACTION`, text: `Normal damage. The target triggers reactions as if it just used a move action. It is also flat-footed until the end of its next turn.`},
    {name: `CLEAN THROUGH`, text: `Triple damage.`},
    {name: `CHEEK PIERCED`, text: `The target must succeed at a DC 5 flat check to cast spells with a verbal component until healed.`},
    {name: `HEAD SHOT`, text: `Triple damage. **Crit Effect:** The target must succeed at a Fortitude save or die.`},
    {name: `SPINAL TAP`, text: `Normal damage. **Crit Effect:** The target is sickened 3.`},
    {name: `HEART SHOT`, text: `Triple damage. **Crit Effect:** The target takes 1d4
    persistent bleed damage.`},
    {name: `NAILED IN PLACE`, text: `As the bow critical specialization effect. If this is a melee weapon, you must drop the weapon to gain this effect. If this attack already has that effect, the Athletics check to pull free is DC 20 instead of DC 10.`},
    {name: `JAVELIN CATCHER`, text: `Triple damage if the attack was a ranged or thrown attack. Double damage for all other attacks.`},
    {name: `INFECTION`, text: `The target must succeed at a Fortitude save or contract filth fever (Bestiary pg. 258).`},
    {name: `EYE PATCH FOR YOU`, text: `Triple damage. **Crit Effect:** The target is dazzled until healed.`},
    {name: `KNOCKBACK`, text: `The target is pushed 10 feet.`},
    {name: `SPUN AROUND`, text: `The target is flat-footed until the end of its next turn.`},
    {name: `GRAZING HIT`, text: `Normal damage. **Crit Effect:** The target is stunned 3.`},
    {name: `PENETRATING WOUND`, text: `The attack ignores all resistances.`},
    {name: `GUSHER`, text: `The target takes 1d6 persistent bleed damage.`},
    {name: `DEEP HURTING`, text: `**Crit Effect:** The target is fatigued.`},
    {name: `HOBBLED`, text: `**Crit Effect:** Until healed, the target is clumsy 2 and takes a -10-foot status penalty to all Speeds.`},
    {name: `PERFECT STRIKE`, text: `Triple damage.`},
    {name: `DEEP WOUND`, text: `**Crit Effect:** The target is sickened 3.`},
    {name: `TENACIOUS WOUND`, text: `Normal damage. **Crit Effect:** The target can't heal this damage until it has rested at least 8 hours.`},
    {name: `LEG WOUND`, text: `**Crit Effect:** The target takes a -5-foot status penalty to its land Speed until healed.`},
    {name: `ORGAN SCRAMBLE`, text: `Triple damage. **Crit Effect:** The target is fatigued.`},
    {name: `BICEP WOUND`, text: `The target is enfeebled 1 until healed.`},
    {name: `RAGGED WOUND`, text: `The target takes 1d6 persistent bleed damage.`},
  ]],
  ['slashing', [
    {name: `SURPRISE OPENING`, text: `**Crit Effect:** You gain 1 action that you can use before the end of your turn to use an attack action against the target.`},
    {name: `MISSING EAR`, text: `Normal damage. The target takes a -2 circumstance penalty to Perception checks and Charisma-based checks except Intimidation until healed.`},
    {name: `BROW TO CHIN`, text: `**Crit Effect:** The target takes a -2 status penalty to Perception and ranged attack rolls until healed.`},
    {name: `GORY`, text: `The target is sickened 1.`},
    {name: `HAMSTRING`, text: `Normal damage. **Crit Effect:** The target is knocked prone. The target is also clumsy 2 until healed.`},
    {name: `UGLY WOUND`, text: `The target takes a -2 circumstance penalty to checks with all Charisma-based skills except Intimidation.`},
    {name: `MOMENTUM`, text: `You gain a +2 circumstance bonus to all attack rolls until the end of your next turn.`},
    {name: `SHATTERED JAW`, text: `**Crit Effect:** Until healed, the target is wounded 1 and can't speak, eat, drink, or make attacks with its jaws.`},
    {name: `TANGLED`, text: `**Crit Effect:** You can attempt to Grapple the target as a free action. This uses the same multiple attack penalty as your attack and doesn't count toward your multiple attack penalty.`},
    {name: `DISEMBOWEL`, text: `Triple damage.`},
    {name: `WEAPON STRIKE`, text: `**Crit Effect:** Deal normal damage to one of the target's weapons (applying Hardness normally).`},
    {name: `MISSING DIGITS`, text: `Normal damage. **Crit Effect:** The target loses 1d4 fingers on one hand and becomes clumsy 1 until subject to a regeneration spell or similar effect.`},
    {name: `OVERHAND CHOP`, text: `**Crit Effect:** 1d8 persistent bleed damage.`},
    {name: `THROAT SLASH`, text: `Normal damage. **Crit Effect:** The target takes 1d8 persistent bleed damage. The target can't talk, cast spells with a verbal component, or breathe while subject to this bleed damage.`},
    {name: `STAND ASIDE`, text: `Push the target 5 feet.`},
    {name: `CUT STRAPS`, text: `**Crit Effect:** The target's armor check penalty doubles until the armor is Repaired (DC 15).`},
    {name: `KNOCKBACK`, text: `Push the target up to 10 feet.`},
    {name: `SEVERED TENDON`, text: `**Crit Effect:** Until healed, the target is clumsy 1 and takes a -5-foot status penalty to its land Speed.`},
    {name: `THAT'LL LEAVE A MARK!`, text: `Normal damage. **Crit Effect:** The target takes 2d6 persistent bleed damage.`},
    {name: `FINGERTIPPED`, text: `Normal damage. Until healed, the target is clumsy 1 and can't use one of its hands (chosen randomly by the GM).`},
    {name: `RUPTURE ABDOMINAL CAVITY`, text: `Triple damage. The target is fatigued.`},
    {name: `PAIN AND SIMPLE`, text: `Triple damage.`},
    {name: `CARVE YOUR INITIALS`, text: `Normal damage. The target is so humiliated it can do nothing but attack you. At the end of each of its turns, it can attempt a Will save to end this effect.`},
    {name: `LEAN INTO THE BLOW`, text: `Triple damage. You drop your weapon.`},
    {name: `HACK AND SLASH`, text: `Triple damage. The target is flat-footed until the end of its next turn.`},
    {name: `SEVERED SPINE`, text: `**Crit Effect:** The target must succeed at a Fortitude save or be paralyzed until healed.`},
    {name: `LONG GASH`, text: `Normal damage. **Crit Effect:** The target takes 1d4 persistent bleed damage. The DC of the flat check to remove this bleed damage is 5 higher than normal.`},
    {name: `BROAD SWIPE`, text: `The target takes 1d4 persistent bleed damage.`},
    {name: `PAPER CUT`, text: `The target takes a -2 status penalty to attack rolls until the end of its next turn.`},
    {name: `WIDE OPEN`, text: `The target is flat-footed until the end of its next turn.`},
    {name: `ACROSS THE EYES`, text: `Normal damage. **Crit Effect:** The target is blinded until healed.`},
    {name: `FROM CHOPS TO GROIN`, text: `Triple damage. **Crit Effect:** The target must succeed at a Fortitude save or die.`},
    {name: `NERVE SLICE`, text: `**Crit Effect:** The target is slowed 2 for 1 round.`},
    {name: `LEG SWIPE`, text: `The target is knocked prone.`},
    {name: `DECAPITATION`, text: `Triple damage. **Crit Effect:** The target must succeed at a Fortitude save or die.`},
    {name: `LIP CUT`, text: `The target must succeed at a DC 5 flat check to cast spells with a verbal component until healed.`},
    {name: `FLAY`, text: `Normal damage. The target is enfeebled 3 until healed.`},
    {name: `FLAT-BLADE THWACK`, text: `Triple damage. You can deal bludgeoning damage instead of slashing damage.`},
    {name: `ARMOR DAMAGE`, text: `The target's armor also takes the damage (applying the armor's Hardness normally).`},
    {name: `SLICED HAND`, text: `Normal damage. Until healed, the target is enfeebled 1, clumsy 1, and can't use one of its hands (determined randomly by the GM).`},
    {name: `SWING THROUGH`, text: `**Crit Effect:** Make an additional attack against a foe adjacent to the original target, using the same attack modifier as the original attack.`},
    {name: `MUSCLE WOUND`, text: `**Crit Effect:** The target is enfeebled 2 until healed.`},
    {name: `TERRIBLE CUT`, text: `Triple damage.`},
    {name: `GUT SLASH`, text: `The target takes 1d4 persistent bleed damage and any creature it Swallows Whole is immediately released.`},
    {name: `BAD PARRY`, text: `**Crit Effect:** The target must succeed at a Reflex save or drop one weapon it is holding (determined randomly by the GM).`},
    {name: `SAPPING SLASH`, text: `**Crit Effect:** The target is fatigued.`},
    {name: `BROW CUT`, text: `Normal damage. **Crit Effect:** The target takes 1d4 persistent bleed damage. Until the bleed ends, all creatures are concealed to the target.`},
    {name: `PARRYING STRIKE`, text: `**Crit Effect:** Gain a +2 circumstance bonus to AC until the end of your next turn.`},
    {name: `SPUN AROUND`, text: `The target is flat-footed until the end of its next turn.`},
    {name: `WING TEAR`, text: `The target loses any fly Speed until healed.`},
    {name: `BEWILDERING DISPLAY`, text: `**Crit Effect:** The target is flat-footed until the end of its next turn.`},
    {name: `DELAYED WOUND`, text: `Normal damage. **Crit Effect:** The target takes the same amount of damage at the ends of its next two turns.`},
  ]],
  ['bomb-or-spell', [
    {name: `ALLERGIC REACTION`, text: `The target takes 1d8 poison damage.`},
    {name: `MIND CLOUD`, text: `The target is stupefied 2 until healed.`},
    {name: `OLFACTORY OVERLOAD`, text: `The target loses its sense of smell and any scent ability or other olfactory senses until healed.`},
    {name: `STUNNED`, text: `Normal damage. The target is stunned 2.`},
    {name: `CUT OFF FROM MAGIC`, text: `Normal damage. The target can't cast spells or activate magic items for 1d4 rounds.`},
    {name: `NOW YOU SEE ME...`, text: `You become invisible until the end of your next turn or until you use a hostile action.`},
    {name: `PETRIFIED`, text: `The target is petrified for 10 minutes.`},
    {name: `PROTECTIVE CHARM`, text: `You gain a +2 status bonus to AC and all saving throws until the end of your next turn.`},
    {name: `PRETTY COLORS`, text: `The target is dazzled until the end of your next turn.`},
    {name: `CONDUIT`, text: `The target takes a -2 status penalty to AC and saves against your bombs or spells until the end of your next turn.`},
    {name: `NERVE DAMAGE`, text: `Normal damage. The target is slowed 1 until healed.`},
    {name: `STRANGE GOO`, text: `Normal damage and the target is restrained, using your class DC as the DC to Escape.`},
    {name: `KNOCKBACK`, text: `Push the target up to 10 feet.`},
    {name: `LIFE LEECH`, text: `If this is a spell, the target becomes doomed 1 and you regain 1d8 Hit Points.`},
    {name: `VAMPIRIC FEEDBACK`, text: `Normal damage. You regain Hit Points equal to half the damage you dealt.`},
    {name: `ELECTROCUTED`, text: `If this is a electricity spell or bomb, the target takes double damage, and at the start of its next turn, it takes normal damage. Any other bomb or spell deals double damage.`},
    {name: `FROZEN`, text: `If this is a cold bomb or spell, the target takes triple damage and is slowed 2 for 1 round. Any other bomb or spell deals double damage.`},
    {name: `POWER SURGE`, text: `Triple damage.`},
    {name: `DEVASTATING STRIKE`, text: `Triple damage. The target is stunned 1.`},
    {name: `EYEBURN`, text: `The target is blinded until the end of its next turn.`},
    {name: `TRANSPOSITION`, text: `If this is a spell attack, you and the target switch places. This is a teleportation effect.`},
    {name: `HYPNOTIC LINK`, text: `If this is a spell, the target takes normal damage and is controlled by you until the end of its next turn.`},
    {name: `DISTRACTION`, text: `The target is flat-footed until the end of its next turn.`},
    {name: `FUNNY BONE`, text: `The target laughs uncontrollably until the end of its next turn. While laughing, it is slowed 1 and can't use reactions.`},
    {name: `SHRINK AFTEREFFECT`, text: `Normal damage. The target is reduced in size as if subject to a shrink spell (CRB pg. 369) until the end of its next turn.`},
    {name: `PSYCHIC OVERFLOW`, text: `The target takes 1d8 mental damage.`},
    {name: `VULNERABILITY`, text: `The target gains weakness 5 to any damage types dealt by the bomb or spell for 1 minute.`},
    {name: `LINGERING DAMAGE`, text: `The target takes 1d6 persistent damage of the same type as the bomb or spell's damage.`},
    {name: `UNNATURAL SELECTION`, text: `Triple damage to aberrations, celestials, fiends, and monitors. Double damage to all other creatures.`},
    {name: `HOARDER'S WRATH`, text: `Triple damage to dragons. Double damage to all other creatures.`},
    {name: `SLOWED DOWN`, text: `The target is slowed 2 for 1 round.`},
    {name: `DOOMED!`, text: `The target is slowed 1 for 1 round, and is also doomed 1.`},
    {name: `FORCEFUL BLAST`, text: `The bomb or spell deals an additional 1d8 force damage.`},
    {name: `TERRIFYING DISPLAY`, text: `The target is frightened 3.`},
    {name: `RETURNING SPELL`, text: `If a spell attack, the spell or spell slot is not expended.`},
    {name: `CALL OF THE WILD`, text: `Triple damage to animals, beasts, and fey. Double damage to all other creatures.`},
    {name: `CORROSIVE`, text: `If this is an acid bomb or spell, the target takes triple damage and 1d6 persistent acid damage. Any other bomb or spell deals double damage.`},
    {name: `MAGICAL GLOW`, text: `The target glows for 1 minute with the effect of a faerie fire spell.`},
    {name: `DRAINING STRIKE`, text: `The target loses one random prepared spell or spell slot, as determined by the GM.`},
    {name: `COMBUSTION`, text: `If this is a fire bomb or spell, the target takes triple damage and 1d6 persistent fire damage. Any other bomb or spell deals double damage.`},
    {name: `MAXIMUM EFFECT`, text: `Don't roll for damage. You deal the maximum possible critical hit damage with this attack.`},
    {name: `INTENSE STRIKE`, text: `The attack ignores all resistances.`},
    {name: `EXCRUCIATING`, text: `The target is sickened 3.`},
    {name: `INTENSE SPLASH`, text: `The target takes normal damage, and all creatures adjacent to the target take half damage of the same type.`},
    {name: `PLANAR RIFT`, text: `If this is a spell, the target takes normal damage and must succeed at a Will save or be sent to a random plane (determined by the GM).`},
    {name: `LIGHT BLAST`, text: `The target is blinded until the end of its next turn.`},
    {name: `MYSTICAL THWART`, text: `The target can't activate magic items, cast spells, or use Quick Alchemy until the end of its next turn.`},
    {name: `PHASED`, text: `The target becomes incorporeal (Bestiary pg. 346) until the end of your next turn.`},
    {name: `TIME VORTEX`, text: `If this is a spell, normal damage and the target vanishes and reappears 1d4 rounds later. The target can use no actions, and any effects it has with durations do not pass while it's gone.`},
    {name: `ENERGY MIGHT`, text: `If the bomb or spell deals acid, cold, electricity, fire, or sonic damage, it deals triple damage. Any other bomb or spell deals double damage.`},
    {name: `ROARING BLAST`, text: `The target is deafened until healed.`},
    {name: `CONCUSSIVE BLAST`, text: `The target is pushed up to 10 feet and knocked prone.`},
  ]]
]);

module.exports = {
  data: new SlashCommandBuilder()
    .setName('critical-hit')
    .setDescription('Displays a random effect from the Critical Hit deck.').addStringOption(option =>
      option.setName('source')
        .setDescription('Source of the critical hit.')
        .setRequired(true)
          .addChoice('Bludgeoning', 'bludgeoning')
          .addChoice('Piercing', 'piercing')
          .addChoice('Slashing', 'slashing')
          .addChoice('Bomb or Spell', 'bomb-or-spell')),

  async execute(interaction) {

    let source = interaction.options.getString('source');

    let effectsArray = effectsMap.get(source);
    let effect = effectsArray[Math.floor(Math.random()*effectsArray.length)];

    const embed = new MessageEmbed()
      .setColor('#209CEE')
      .setTitle(Utils.capitalizeWords(effect.name))
      .setURL(`https://paizo.com/products/btq024tn?Pathfinder-Critical-Hit-Deck`)
      .setDescription(effect.text)
      .setFooter({
        text: (source == 'bomb-or-spell' ? 'Bomb or Spell' : Utils.capitalizeWords(source) ) });
    
    interaction.reply({ embeds: [embed], ephemeral: false });

  },
};