const { SlashCommandBuilder } = require('@discordjs/builders');
const { MessageActionRow, MessageButton, MessageEmbed, MessageSelectMenu } = require('discord.js');

const fetch = require('node-fetch');
const { apiUrl, apiKey } = require('../config.json');

const Utils = require('../utils.js');

let effectsMap = new Map([
  ['melee', [
    {name: `MEANT TO DO THAT`, text: `You are moved 10 feet in a random direction (determined by the GM). This movement triggers reactions.`},
    {name: `WRONG END`, text: `If you are using a slashing weapon, you take 106 slashing damage and 1 persistent bleed damage.`},
    {name: `BAD FALL`, text: `You fall prone and are slowed 1 until the end of your next turn.`},
    {name: `WAIT, WHAT?`, text: `You are confused.`},
    {name: `BAD GRIP`, text: `You take a -2 circumstance penalty to attack rolls with this weapon until the end of your next turn.`},
    {name: `EAT DIRT`, text: `You fall prone and are blinded until the end of your next turn.`},
    {name: `VIBRATION`, text: `If you're using a bludgeoning weapon, you drop that weapon and become enfeebled 2 until healed`},
    {name: `WHO WAS THAT?`, text: `You are slowed 1 until the end of your next turn.`},
    {name: `ATTACK THE DARKNESS`, text: `Your enemies are concealed from you until the end of your next turn.`},
    {name: `OFF BALANCE`, text: `You take a -2 circumstance penalty to attack rolls until the end of your next turn.`},
    {name: `SLIPPED`, text: `You fall prone.`},
    {name: `SECOND THOUGHTS`, text: `You are sickened 3.`},
    {name: `BUTTERFINGERS`, text: `You drop the weapon you made the attack with.`},
    {name: `NOTCHED`, text: `Your weapon takes 1d6 damage, ignoring Hardness.`},
    {name: `BROKEN WEAPON`, text: `You weapon's current Hit Points are reduced to its Broken Threshold. If already broken, the weapon takes 3d6 damage, ignoring Hardness.`},
    {name: `FLING`, text: `You drop the weapon you used for the attack. 'It lands 1d6x5 feet away from you in a random direction.`},
    {name: `PULLED MUSCLE`, text: `Until healed, you are enfeebled 2.`},
    {name: `OVEREXTENDED`, text: `You trigger reactions as if you had used a move action.`},
    {name: `AWKWARD ATTACK`, text: `You are flat-footed until the end of your next turn.`},
    {name: `THIS SWORD IS HEAVY`, text: `You are fatigued.`},
    {name: `BACKSWING`, text: `You deal the attack's normal damage to yourself instead of the target.`},
    {name: `WIDE OPEN`, text: `You are flat-footed until the end of your next turn.`},
    {name: `STRAINED`, text: `Until healed, you are clumsy 2.`},
    {name: `TOO MUCH STUFF!`, text: `You get tangled in your gear and are encumbered until you spend 2 Interact actions to free yourself.`},
    {name: `SPINNING SWING`, text: `You are sickened 2.`},
    {name: `I TOLD YOU IT'S SHARP!`, text: `You take 1d6 persistent bleed damage.`},
    {name: `PIN PRICK`, text: `You take 1 persistent bleed damage.`},
    {name: `ARMOR SMASH`, text: `Your deal the attack's normal damage to your armor, applying Hardness.`},
    {name: `CATCH YOUR BREATH`, text: `You are slowed 2 until the end of your next turn.`},
    {name: `GRAVE MISCALCULATION`, text: `You critically hit yourself with the attack.`},
    {name: `STUCK`, text: `Your weapon is lodged into a nearby surface or item. To free it, you must succeed at a DC 20 Athletics check made as an Interact action.`},
    {name: `BENT`, text: `You weapon's current Hit Points are reduced to its Broken Threshold. If already broken, the weapon takes 3d6 damage, ignoring Hardness.`},
    {name: `FUNNY BONE`, text: `You drop one item you are holding (determined randomly by the GM).`},
    {name: `WEAPON TANGLE`, text: `You can't use this weapon to attack until the end of your next turn.`},
    {name: `BONK!`, text: `You are stunned 2.`},
    {name: `SORRY!`, text: `You hit an ally adjacent to you or an ally adjacent to the target.`},
    {name: `BETTER TO GIVE`, text: `You hit yourself instead of the target.`},
    {name: `RANG YOUR OWN BELL`, text: `Until healed, you are deafened.`},
    {name: `ON THE RECEIVING END`, text: `You deal damage to yourself instead of the target.`},
    {name: `CREEPING HESITATION`, text: `You are flat-footed until the end of your next turn.`},
    {name: `ALL OR NOTHING`, text: `You take a -1 circumstance penalty to attack rolls until you score a critical hit.`},
    {name: `WINDED`, text: `You are fatigued.`},
    {name: `SHIELD CRASH`, text: `Your deal the attack's normal damage to your shield, applying Hardness`},
    {name: `HAND IT OVER`, text: `Unless you succeed at a Reflex saving throw, your target gains possession of your weapon.`},
    {name: `THIS IS BAD`, text: `You take 1d10 persistent bleed damage.`},
    {name: `CLIPPED YOUR HAND`, text: `You take 1d8 persistent bleed damage.`},
    {name: `DECISION PARALYSIS`, text: `You are slowed 1 until the end of your next turn.`},
    {name: `CATASTROPHIC FAILURE`, text: `You fall unconscious until you wake up or the end of your next turn.`},
    {name: `POINTY END GOES THERE`, text: `You become wounded 1 or your wounded value increases by 1.`},
    {name: `BROKEN HAFT`, text: `You weapon's current Hit Points are reduced to its Broken Threshold. If already broken, the weapon takes 3d6 damage, ignoring Hardness. If your weapon is a reach weapon, it loses reach.`},
    {name: `FOG OF WAR`, text: `You are dazzled until the end of your next turn.`},
    {name: `GO FOR THE EYES`, text: `You are dazzled until the end of your next turn.`},
    {name: `PUNT`, text: `Your weapon flies 1d4x5 feet in a random direction (determined by the GM).`},
  ]],
  ['ranged', [
    {name: `MISJUDGED THE DISTANCE`, text: `Until the end of your next turn, all your range increment penalties are doubled.`},
    {name: `PHANTOM WIND`, text: `You take a -2 circumstance penalty to ranged attacks until the end of your next turn.`},
    {name: `SPRAINING SHOT`, text: `Until healed, you take a -10-foot circumstance penalty to your land Speed and are clumsy 1.`},
    {name: `DON'T HIT ME!`, text: `Until the end of your next turn, each time you miss with a ranged attack targeting enemy adjacent to any of your allies, you hit one of those adjacent allies instead (determined randomly by the GM).`},
    {name: `HUH?`, text: `You are confused.`},
    {name: `OVERCOMPENSATE`, text: `Cover provides a +4 circumstance bonus to AC against your ranged attacks for 1 minute.`},
    {name: `RECOIL`, text: `You are pushed 5 feet backwards and fall prone.`},
    {name: `SEEING DOUBLE`, text: `You are dazzled until the end of your next turn.`},
    {name: `AIM CAREFULLY NEXT TIME`, text: `Until the end of your next turn, your attacks require an extra action to use.`},
    {name: `FRIENDLY FIRE`, text: `You hit the ally nearest to the target.`},
    {name: `BACKFIRE`, text: `You hit yourself instead of the target.`},
    {name: `MIX IT UP`, text: `You can't make ranged attacks until the end of your next turn.`},
    {name: `SNAPPED STRING`, text: `If the attack used a weapon in the bow group, the string snaps, requiring 3 Interact actions to fix.`},
    {name: `NOTCHED FINGERS`, text: `You take 1d4 persistent bleed damage.`},
    {name: `MY SPLEENY BITS!`, text: `You become wounded 1 or your wounded value increases by 1.`},
    {name: `HEAD RUSH`, text: `You are sickened 2.`},
    {name: `AWKWARD ATTACK`, text: `You are flat-footed until the end of your next turn.`},
    {name: `ACHING BACK`, text: `You are fatigued.`},
    {name: `SHOT YOUR EYE OUT`, text: `You critically hit yourself instead of the target.`},
    {name: `ERRANT AIM`, text: `Reroll the attack roll, targeting the creature closest to the target (excluding yourself).`},
    {name: `WIDE OPEN`, text: `You are flat-footed until the end of your next turn.`},
    {name: `CRACKED`, text: `The ranged weapon (not the ammunition you are using takes 1d6 damage, ignoring Hardness.`},
    {name: `WHOOPS!`, text: `You fall prone.`},
    {name: `SPRAIN`, text: `Until healed, you are clumsy 2.`},
    {name: `NICKED`, text: `You take 1 persistent bleed damage.`},
    {name: `KLUTZ`, text: `You drop the weapon you used.`},
    {name: `SPILLED AMMO`, text: `The ammunition from the weapon you're using falls from its container onto the ground. You can spend 1 Interact action to pick up one piece of ammunition spilled this way.`},
    {name: `LOST GRIP`, text: `You are slowed 2 until the end of your next turn.`},
    {name: `WRONG WEAPON`, text: `If you made a thrown attack, you instead throw an object from your gear (determined randomly by the GM).`},
    {name: `KICKBACK LIKE A MULE`, text: `You fall prone.`},
    {name: `ARCHER'S ELBOW`, text: `Until healed, you take a -2 circumstance penalty to ranged attacks.`},
    {name: `DOUBLE MISS`, text: `If this attack uses ammunition, you use twice the amount of ammunition on this attack.`},
    {name: `NOT MY PONY!`, text: `You hit the nearest animal companion, mount, or familiar.`},
    {name: `AMAZING MISS`, text: `You are stunned 1.`},
    {name: `SHOT YOUR FOOT`, text: `Until healed, you are clumsy 2 and take a -5-foot circumstance penalty to your land Speed.`},
    {name: `LOST THE TARGET`, text: `You take a -2 circumstance penalty to attack rolls until the end of your next turn.`},
    {name: `WEAPON PROBLEM`, text: `If the attack used a projectile weapon, something on the weapon malfunctions, requiring you to spend 2 Interact actions to fix.`},
    {name: `LOWERED GUARD`, text: `You provoke reactions as if you used a move action.`},
    {name: `IN THE LINE OF FIRE`, text: `You critically hit your nearest ally.`},
    {name: `INSECURE`, text: `You take a -1 circumstance penalty to attack rolls until you score a critical hit.`},
    {name: `CLOSE TO THE EAR`, text: `You are deafened until the end of your next turn.`},
    {name: `BAD ALIGNMENT`, text: `You take a -2 circumstance penalty to attacks using this weapon until the end of your next turn.`},
    {name: `EVERYTHING YOU GOT`, text: `You are fatigued.`},
    {name: `BROKEN`, text: `You weapon's current Hit Points are reduced to its Broken Threshold. If already broken, the weapon takes 3d6 damage, ignoring Hardness.`},
    {name: `WHAT ARE THE ODDS?`, text: `If this is a thrown weapon attack and the target can hold the weapon, the target snatches the weapon out of the air and wields it.`},
    {name: `OOPSIE!`, text: `You hit yourself instead of the target.`},
    {name: `TORN TENDON`, text: `Until healed, you are clumsy 2.`},
    {name: `OVERTHROW`, text: `If the attack used a thrown weapon, the weapon travels three times its range increment in a random direction (determined by the GM).`},
    {name: `TUNNEL VISION`, text: `For 3 rounds, you gain a +1 circumstance bonus to attack rolls, but you are flat-footed.`},
    {name: `ALL THUMBS`, text: `Until healed, you are clumsy 1.`},
    {name: `BULL'S EYE`, text: `Your attack ricochets and hits you near the eye. You are blinded until the end of your next turn.`},
    {name: `PINCH A FINGER`, text: `You take 1d6 persistent bleed damage.`},
    {name: `SO MUCH BLOOD`, text: `You are sickened 3.`},
  ]],
  ['unarmed', [
    {name: `NOT THE WEAK POINT`, text: `You take 1d6 persistent bleed damage and can't use this attack until the end of your next turn.`},
    {name: `OVERTHINK IT`, text: `You target gains a +2 circumstance bonus to AC against attacks you make against it until the end of your next turn.`},
    {name: `BAD JAM`, text: `You are clumsy 1 and enfeebled 2.`},
    {name: `PINCHED NERVE`, text: `Until healed, you take a -10-foot circumstance penalty to land Speed and are clumsy 1.`},
    {name: `EYE STRAIN`, text: `You are dazzled until the end of your next turn.`},
    {name: `THAT TASTES AWFUL!`, text: `If this was a jaws attack (or similar), you are sickened 3.`},
    {name: `PUNCTURED FOOT`, text: `You take 1d4 persistent bleed damage. Until this effect ends, you take a -10-foot circumstance penalty to your land Speed.`},
    {name: `BROKEN TOOTH`, text: `Until healed, you take a -2 circumstance penalty to attack rolls.`},
    {name: `BRUTAL COLLISION`, text: `Attempt a Fortitude saving throw. If you succeed, you're stunned 1. If you fail, you're stunned 2.`},
    {name: `SOMETHING'S BROKEN`, text: `You take 1d4 bludgeoning damage, and you can't use this attack until healed.`},
    {name: `BRUISED EGO`, text: `You can't attack another creature until the target is knocked out or the end of your next turn.`},
    {name: `HANGNAIL`, text: `If you attacked with a claw or fist, you can't use that attack until the end of your next turn.`},
    {name: `TORN MUSCLE`, text: `Until healed, you are enfeebled 1.`},
    {name: `HIT THE WALL`, text: `You are fatigued.`},
    {name: `FRUSTRATION`, text: `You take a -2 circumstance penalty to attack rolls until the end of your next turn.`},
    {name: `OVEREXTENDED`, text: `You trigger reactions as if you had used a move action.`},
    {name: `BIT YOUR TONGUE!`, text: `You take 1 persistent bleed damage.`},
    {name: `UPSET STOMACH`, text: `You are sickened 2.`},
    {name: `TIRING ATTACK`, text: `You are fatigued.`},
    {name: `AWKWARD ATTACK`, text: `You are flat-footed until the end of your next turn.`},
    {name: `TRIPPED`, text: `You fall prone.`},
    {name: `FIST MEET FACE`, text: `You critically hit yourself with the attack.`},
    {name: `OUT OF POSITION`, text: `You can't use this attack until the end of your next turn.`},
    {name: `BLEEDING FIST`, text: `You take 1d6 persistent bleed damage.`},
    {name: `TWISTED UP`, text: `You are encumbered until you spend 2 Interact actions to free yourself.`},
    {name: `STOP HITTING YOURSELF`, text: `You hit yourself instead of the target.`},
    {name: `JUST A TASTE`, text: `You hit an ally adjacent to you or the target.`},
    {name: `BATTERED`, text: `Until healed, you take a -2 circumstance penalty to checks and saving throws.`},
    {name: `GOT TOO CLOSE`, text: `This attack grants and triggers a Grapple or Grab as a reaction by your enemy.`},
    {name: `CAN'T FIND AN OPENING`, text: `You can't use this attack until the end of your next turn.`},
    {name: `OFF BALANCE`, text: `You are slowed 2 until the end of your next turn.`},
    {name: `CAUGHT YOUR ATTACK`, text: `This attack grants and triggers a Trip or Shove as a reaction by your enemy.`},
    {name: `BAD HEADBUTT`, text: `You are stunned 1.`},
    {name: `BONE BRUISE`, text: `You become wounded 1 or your wounded value increases by 1.`},
    {name: `OVEREXERTION`, text: `You are fatigued.`},
    {name: `SPRAIN`, text: `Until healed, you are clumsy 2.`},
    {name: `SNEEZE`, text: `You are slowed 1 until the end of your next turn.`},
    {name: `FEROCIOUS FUMBLE`, text: `Your critically hit an ally within your reach (determined randomly by the GM).`},
    {name: `HEAD, MEET WALL`, text: `You are stunned 1.`},
    {name: `GREAT ROAR`, text: `Until healed, you are deafened.`},
    {name: `PINS AND NEEDLES`, text: `You are sickened 3.`},
    {name: `IT BIT YOUR FIST`, text: `The target deals jaws damage to you.`},
    {name: `HARD-EDGED ADVERSARY`, text: `You take 2d6 piercing or slashing damage (determined by the GM).`},
    {name: `SMASH THE FLOOR`, text: `You kick up a cloud of dust, becoming blinded until the end of your next turn.`},
    {name: `WHIRLWIND OF SHAME`, text: `You hit every creature adjacent to you except for the target.`},
    {name: `INGROWN NAIL`, text: `You take a -1 circumstance penalty to attack rolls until you score a critical hit.`},
    {name: `STINGING FAILURE`, text: `Until healed, you take a -2 circumstance penalty to attack rolls made with this attack.`},
    {name: `DON'T PICK AT IT`, text: `You become wounded 1 or your wounded value increases by 1.`},
    {name: `HEAD FIRST!`, text: `You fall unconscious until you wake up or the end of your next turn.`},
    {name: `WHIFF`, text: `You hit yourself instead of the target.`},
    {name: `JAM A FINGER`, text: `You hit the target for the minimum amount of damage you can deal with the attack. You take the attack's normal damage.`},
    {name: `WINDS OF CHANGE`, text: `You can't attack the same target again until the end of your next turn.`},
    {name: `UNINTENTIONAL MOVE`, text: `You are moved 10 feet in a random direction (determined by the GM). This movement triggers reactions.`},
  ]],
  ['spell', [
    {name: `HOW DID THAT HAPPEN?`, text: `You call forth a mist with the effects of stinking cloud centered on a corner of your space (determined randomly by the GM).`},
    {name: `POWER DOWN`, text: `Until healed, you are stupefied 2.`},
    {name: `EXPLODING SKULL`, text: `You must attempt a Fortitude save. If you succeed, you take 3d6 mental damage. If you fail, your head explodes and you die.`},
    {name: `MENTAL SLIP`, text: `You are controlled by the target until the end of your next turn.`},
    {name: `BLASTOFF`, text: `You must succeed at a Will saving throw or be thrown 1d6x5 feet into the air or in a random direction determined by the GM if you are flying).`},
    {name: `STRANGE TRANSFERENCE`, text: `Lose one prepared spell or spell slot, determined randomly by the GM. Your target can Cast this Spell on its next turn even if they can't cast spells, using your level, spell attack modifier, and spell DC.`},
    {name: `MENTAL BACKLASH`, text: `Until healed, you are stupefied 3.`},
    {name: `FRAGMENTED MAGIC`, text: `Your target gains the effect of a mirror image spell.`},
    {name: `POWER TRANSFER`, text: `The highest-level beneficial spell effect currently affecting you is transferred to your target.`},
    {name: `POWER DRAIN`, text: `You lose one prepared spell or spell slot (determined randomly by the GM).`},
    {name: `NOSEBLEED.`, text: `You take 1 persistent bleed damage.`},
    {name: `MAGIC VACUUM`, text: `The effects of all beneficial spells affecting you end immediately.`},
    {name: `MAGIC FATIGUE`, text: `You can't cast any spells until the end of your next turn.`},
    {name: `ELECTRICAL FEEDBACK`, text: `You take 2d6 electricity damage.`},
    {name: `BEASTLY RIFT`, text: `Your spell becomes a summon animal spell of the same level. The animal attacks you.`},
    {name: `REFLECTION`, text: `The spell hits you instead of the target.`},
    {name: `SPONTANEOUS COMBUSTION`, text: `You take 2d6 fire damage.`},
    {name: `CRITICAL BACKLASH`, text: `You critically hit yourself instead of the target.`},
    {name: `ACIDIC BACKLASH`, text: `You take 2d6 acid damage.`},
    {name: `BLEEDING EYES`, text: `You take 1d6 persistent bleed damage.`},
    {name: `TANGLED IN YOUR GEAR`, text: `You are encumbered until you spend 2 Interact actions to free yourself.`},
    {name: `DISTANCE RIFT`, text: `You are teleported to the nearest space adjacent to your spell's target.`},
    {name: `MIND DRAIN`, text: `Until healed, you are stupefied 1.`},
    {name: `VERTIGO`, text: `You are sickened 2.`},
    {name: `APPRENTICE MOVE`, text: `Reroll the attack roll, targeting the creature closest to the target (excluding yourself).`},
    {name: `NOT ME, YOU FOOL!`, text: `You hit the ally nearest to the target.`},
    {name: `TIRING SPELL`, text: `You are fatigued.`},
    {name: `UNEXPECTED BLAST`, text: `Your spell affects all targets within 30 feet of you. You are immune to this effect.`},
    {name: `YOU MADE 'EM STRONGER`, text: `The target gains a +2 status bonus to attack rolls until the end of its next turn.`},
    {name: `DRAWING A BLANK`, text: `Until healed, you are stupefied 1.`},
    {name: `SPELL SHIELD`, text: `The target gains a +2 status bonus to saving throws against spells for 1 minute.`},
    {name: `LEFT REELING`, text: `You are stunned 1.`},
    {name: `CASTER'S BLOCK`, text: `You can't cast this spell again at any level until you rest and make your daily preparations.`},
    {name: `YOU MADE 'EM BIGGER`, text: `The target increases in size, with the effects of a 2nd-level enlarge spell.`},
    {name: `SIDE EFFECT`, text: `You are sickened 1. You are also stupefied 2 until healed.`},
    {name: `WEAKENED`, text: `You take a -2 circumstance penalty to spell attack rolls and spell DCs until the end of your next turn.`},
    {name: `SPELL RUSH`, text: `You are stupefied 1 until healed.`},
    {name: `THE MAGIC IS GONE`, text: `You take a -1 circumstance penalty to attack rolls until you score a critical hit.`},
    {name: `CAN YOU HEAR ME NOW?`, text: `Until healed, you are deafened.`},
    {name: `ERROR!`, text: `You deal the spell's normal damage to yourself instead of the target.`},
    {name: `WHY ME?`, text: `You provoke reactions as if you used a move action.`},
    {name: `POOR TRADE`, text: `You hit, but you lose a prepared spell or spell slot of the highest level available (you choose the spell).`},
    {name: `YOU MADE 'EM TOUGHER`, text: `The target gains resistance 5 to all damage until the start of its next turn.`},
    {name: `YOU MADE 'EM FASTER`, text: `The target is quickened for 2 rounds.`},
    {name: `JUMBLED COMPONENTS`, text: `You are slowed 2 until the end of your next turn.`},
    {name: `CLATTO VERATA NECKTIE`, text: `You critically hit your nearest ally.`},
    {name: `CURSED`, text: `You are doomed 1.`},
    {name: `MAGICAL SMACKDOWN`, text: `You automatically fail (but do not critically fail) your next saving throw.`},
    {name: `WILD MAGIC`, text: `Roll twice on the rod of wonder table (Pathfinder Core Rulebook 575). You are the target of those effects.`},
    {name: `DRAINING MAGIC`, text: `You are drained 1.`},
    {name: `EVERYTHING TO FEAR`, text: `You are frightened 3.`},
    {name: `NOW I SEE YOU...`, text: `Your target becomes invisible until the end of its next turn or it uses a hostile action.`},
    {name: `IT'S SO SPARKLY!`, text: `You are blinded until the end of your next turn.`},
  ]]
]);

module.exports = {
  data: new SlashCommandBuilder()
    .setName('critical-fumble')
    .setDescription('Displays a random effect from the Critical Fumble deck.').addStringOption(option =>
      option.setName('source')
        .setDescription('Source of the critical fumble.')
        .setRequired(true)
          .addChoice('Melee', 'melee')
          .addChoice('Ranged', 'ranged')
          .addChoice('Unarmed', 'unarmed')
          .addChoice('Spell', 'spell')),

  async execute(interaction) {

    let source = interaction.options.getString('source');

    let effectsArray = effectsMap.get(source);
    let effect = effectsArray[Math.floor(Math.random()*effectsArray.length)];

    const embed = new MessageEmbed()
      .setColor('#209CEE')
      .setTitle(Utils.capitalizeWords(effect.name))
      .setURL(`https://paizo.com/products/btq024ud?Pathfinder-Critical-Fumble-Deck`)
      .setDescription(effect.text)
      .setFooter({ text: Utils.capitalizeWords(source) });
    
    interaction.reply({ embeds: [embed], ephemeral: false });

  },
};